### ISSUE TITLE
[Feat] :package: remove self-hosted runner

### ISSUE THREAD

**Issue by kotamanegi** [Qulacs-Osaka/qulacs-osaka#152]
# 概要
self-hosted runnerの登録を抹消して、完全にGitHub Hosted runnerに移行します。

**Comment by ikanago** [comment]
Linux の runner はすでに offline だったので登録を消しておきました．コンテナのプロセス自体も死んでました．

**Comment by kotamanegi** [comment]
全ての登録を消しました。
