### ISSUE TITLE
wheel build の並列化

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/qulacs-osaka#168]
wheel build を Python のバージョンごとに並列化したいです．可能かどうかはまだ確かめていません．

**Comment by ikanago** [comment]
Python3.6 は security release も終了するのでリリースから外してもよさそうです
> We plan to provide security fixes for Python 3.6 as needed through 2021, five years following its initial release.

https://www.python.org/downloads/release/python-3615/
https://endoflife.date/python

**Comment by ikanago** [comment]
バージョンごとにビルドを並列化するのは問題ないですが，アップロードを並列化するとビルドに失敗したバージョンだけが公開されない状態になる場合があります。
actions/upload-artifact と actions/download-artifact でうまく同期する必要がありそうです。
あるいは，アップロード時には直列ビルド，それ以外のときは並列ビルドだけして結果は破棄，とすればシンプルになります．

**Comment by ikanago** [comment]
ただ，cibuildwheel がバージョンごとの並列ビルドをサポートしていなさそうなので `CIBW_BUILD` を matrix で変えてやるしかないんですが，これをやるとアップロード時だけ直列でやるというのが面倒そうなんですよね...(さすがにアップロード時とそれ以外でジョブを2つ書くのはだるいし)

**Comment by kotamanegi** [comment]
`CIBW_BUILD`の値は更新されるので、新しいバージョンが出た場合は管理が必要になり面倒です。
wheelを高速化する方向性の方が筋が良いと感じたのですがどうでしょうか？

**Comment by ikanago** [comment]
ややこしくなるだけですね...
ubuntu と

**Comment by ikanago** [comment]
cibuildwheel が起動するコンテナの中にキャッシュができるはずで，これを取り出すのが難しそうです

**Comment by kotamanegi** [comment]
Done in https://github.com/qulacs/qulacs/pull/395
