### ISSUE TITLE
Remove build in checking format

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/qulacs-osaka#171]
clang-format を実行する CI ではビルドをする必要はないのでビルドをするステップは除去していいと思います．

**Comment by ikanago** [comment]
@herring101 この前 GitHub Actions のチュートリアルをやったのでこの issue やってみませんか?
実際に動いてるやつをいじってみたほうがいろいろ覚えられると思います

**Comment by herring101** [comment]
ありがとうございます。やってみます！

**Comment by ikanago** [comment]
ビルドをする必要がないというのは，[clang-format を実行する docker image](https://github.com/Qulacs-Osaka/DevOps-OsakaUniv/pkgs/container/qulacs-ubuntu-clang-format) が使えるようになったからなんですが，これに言及してませんでした．すいません 🙇 
というわけで， `cmake --build build --target format` を変更する必要があります．

**Comment by ikanago** [comment]
ただ，問題があって，この docker image は internal で公開されているので，自由には使えないです．
CI で使うには
- PAT を指定する(参考: https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/)
- この image を public にする

このいずれかをやる必要があります．
1つめの方法では，特定の人の PAT に依存するのはその人が辞めたときに更新する必要があるのが面倒です．
2つめの方は，[リポジトリ](https://github.com/Qulacs-Osaka/DevOps-OsakaUniv)は private なのに image が public なのが微妙です．

**Comment by ikanago** [comment]
このさい，DevOps-OsakaUniv から Dockerfile たちを分離して public リポジトリとしてしまうのはアリだと思います

**Comment by herring101** [comment]
とりあえず、clang-format-imageというpublicリポジトリを作って、DevOps-OsakaUnivのREADME以外のファイルをすべて移したのですが、ActionsでのBuildがうまくいきませんでした...
https://github.com/Qulacs-Osaka/clang-format-image/actions/runs/1666777806

**Comment by ikanago** [comment]
ちょっと見てみますね

**Comment by ikanago** [comment]
いらないファイルの削除とリポジトリ名の変更(clang-format 以外のイメージもホストしたいのでそういう名前のほうがよさそうです)をやって master に push しようと思うので，次回の作業のときはまず pull するのを忘れないようにお願いします 🙏

**Comment by ikanago** [comment]
あと，デフォルトブランチを main に変更したので注意してください．

**Comment by herring101** [comment]
ありがとうございます🙇‍♂
一応現時点での進捗を報告しておきます。
```uses: docker://ghcr.io/qulacs-osaka/qulacs-ubuntu-clang-format:latest```
とすると、qulacs-osakaがマウントされずに実行されエラーとなってしまうため、マウントする方法を探したのですがよくわかりませんでした、、、
また明日やります。

**Comment by ikanago** [comment]
mount しないといけないの完全に忘れてましたね...
一応 `container` を使えばあるコンテナ内でコマンドを実行できるようになるんですが([参考](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer))，コンテナには node がインストールされていないため `actions/checkout` などが使えなくなります．
なので
- コンテナ内で直に `git clone` を実行して `/qulacs-osaka` に clone する
- `qulacs_format.sh` を実行

みたいにする必要がありそうです．

想像以上にややこしいことになってしまいました，すいません．
↑で書いた以上に複雑になるようなら現状のワークフローのままにしてこの issue は辞めてしまっていいと思います．

**Comment by herring101** [comment]
時間かかってしまいましたが、おそらくできました！
書いた量は少しだけですが、色んなことを知ることができました。ありがとうございます🙇‍♂

**Comment by herring101** [comment]
できてませんでした、、、
