### ISSUE TITLE
Trigger to run wheel build and Windows CI

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/qulacs-osaka#233]
wheel build と Windows CI は実行時間が30分程度かかり，かなりストレスになっています．
これらは push や PR の更新のたびに実行する必要性が薄いため，PR へのコメントで走るように設定することで CI の待ち時間を減らすことができます．
これは適当な bot を導入することで達成できそうなので，要件に合うものをこれから探します．

**Comment by ikanago** [comment]
bot を導入しなくても，`pull_request_comment` というイベントをトリガーとして CI を実行し，特定の文字列を含まない場合は実行をやめる，としてもよさそうです
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_comment-use-issue_comment

**Comment by ikanago** [comment]
approve をトリガにしてもよさそうです:
https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved

この場合 approve 後に push しても CI が走らないですが，そういう状況で approve を取り消してくれる設定があるようなので，これと組み合わせると merge 前に approve を要求しつつ最新のコードで CI を実行することを強制できそうです．
https://stackoverflow.com/questions/40505904/is-there-a-way-to-make-github-un-approve-a-pull-request-if-a-new-commit-is-pushe

**Comment by ikanago** [comment]
まとめ:

## 設定
`dev` の branch protection rule で
- ubuntu, windows, macos の CI をパスしないとマージできないようにする
- レビュアーが approve した後に commit が push された場合は approve を取り消す

という設定をしたうえで，windows と wheel build のトリガをレビュアーの approve にします．

## メリット
- 時間のかかる CI を何度も実行しなくてよくなる
- bot やスクリプトを導入しなくていい

## 微妙な点
- approve で起動した CI が落ちて修正を push したときに re-run するのに楽な方法がなさそう
  - workflow-dispatch も設定しておけば手動で CI を実行することはできるので，approve を待つ必要はないが，多少面倒

**Comment by ikanago** [comment]
`pull_request_comment` をトリガとする場合も，`if: contains(github.events.comments.body, '[run ci]')` みたいにすればスクリプトを書かなくてもよさそうで，こっちのほうが楽かも知れません

**Comment by KowerKoint** [comment]
> ubuntu, windows, macos の CI をパスしないとマージできないようにする
これまで通り走ったすべてのCIがパスされるだけでいいのではないでしょうか…？
トリガーをapproveにしつつ特定の変更をignoreすればいいと思います。

workflow-dispatchがあればCI落ち修正のre-runはなんとかなりますが、CIを走らせるためだけにコメントを書いてPRを汚すのも微妙だなと思っています…

**Comment by ikanago** [comment]
> これまで通り走ったすべてのCIがパスされるだけでいい

たしかにこれでいいですね．

workflow-dispatch で十分ではあるんですが，ブランチをいちいち選択する必要があるみたいで，何個もあるブランチの中から選ぶ必要があったり走らせるブランチを間違えるおそれがあったりするのが微妙そうです．
とはいえ CI を走らせるためだけにコメントを書くのも微妙ではあるんですよね...
