### ISSUE TITLE
Cannot identify character encoding in some files

### ISSUE THREAD

**Issue by KowerKoint** [Qulacs-Osaka/qulacs-osaka#247]
以下のファイルで、VSCodeやnkfで文字コードを自動識別できないような非ASCIIコメントが存在しています。
エンコーディングがどうなってるかわからない場合は書き直しになるかもしれないです。

- src/cppsim/gate_matrix_diagonal.hpp
- src/cppsim/gate_reflect.hpp
- src/cppsim/gate_reversible.hpp
- src/cppsim/gate_matrix_sparse.hpp

**Comment by KowerKoint** [comment]
@ikanago コメントの書き直しお願いできますか？

**Comment by ikanago** [comment]
ファイルをバイナリで見ると `bf bd ef` というバイト列が多いので調べてみると UTF-8 への変換に失敗した時の文字みたいなのでもとのコメントは失われてそうです 😢 
https://www.fileformat.info/info/unicode/char/0fffd/index.htm

**Comment by WATLE** [comment]
ついでに　merge_circuit　で二つの回路のqubitが違っていても、定義上何の問題もないはずなので、エラー吐かないようにしました
