### ISSUE TITLE
Draw up ReleaseCycle clearly

### ISSUE THREAD

**Issue by KowerKoint** [Qulacs-Osaka/qulacs-osaka#278]
1ヶ月に1回を上限として、devブランチの更新に合わせてマイナーバージョンを上げながらリリースしていく体制を整える。

**Comment by KowerKoint** [comment]
月一の作業を自動化するようなものでもないので、Slackなので「そろそろリリースをしよう」ということを毎月言えるようにしてタグ付けをやればOK

**Comment by ikanago** [comment]
新機能が入るなどしたときはその場でバージョンアップをして，そういうのがなくてもバグ修正くらいはあるので Slackbot にリマインドさせてバージョンアップする，くらいの流れですかね
