### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by KowerKoint** [Qulacs-Osaka/qulacs-osaka#306]
https://github.com/Qulacs-Osaka/qulacs-osaka/blob/6630dffe40717963b9ef1caf73cad702978b51a4/src/cppsim/observable.cpp#L57

リンク切れしてますがこれは無視するしかないですか？

**Comment by Hiroya-W** [comment]
このPDFの中身がどのようなものなのかと、その記述が分からないとURLの置き換えるの難しいですね...

**Comment by Hiroya-W** [comment]
Blame見てると @ikanago さんが知っていそうだけど、1年以上前なのでどうだろう...。

**Comment by ikanago** [comment]
その部分を実装するときに参考にしたんですがリンク切れしてますか...
このあたりに似たような内容が書いてあるので代替になりそうです:
https://en.wikipedia.org/wiki/Lanczos_algorithm
https://math.berkeley.edu/~mgu/MA128BSpring2018/Lanczos.pdf
