### ISSUE TITLE
comment for optimize_light()

### ISSUE THREAD

**Issue by KowerKoint** [Qulacs-Osaka/qulacs-osaka#307]
https://github.com/Qulacs-Osaka/qulacs-osaka/blob/6630dffe40717963b9ef1caf73cad702978b51a4/src/cppsim/circuit_optimizer.hpp#L47-L56

ここのコメント、`optimize()`と同じものになっていて不正確なんですが、`optimize_light()`のやっていることを自分ではうまく言語化できません…

**Comment by WATLE** [comment]
違う点まとめ
・optimize_lightはブロックを指定せず、まとめる前のゲートのうち、後に出てくるほうのサイズ　= まとめた結果のサイズ　ならまとめる。
・optimizeは、合成できなくなるまで何度でもoptimizeする。
・optimize_lightは合成可能なうち、最も後ろだけを検索する。optimizeはすべてについて合成可能か検索する
