### ISSUE TITLE
`ParametricQuantumCircuit` にパラメータ共有を実装する

### ISSUE THREAD

**Issue by ikanago** [Qulacs-Osaka/qulacs-osaka#320]
scikit-qulacs に `ParametricQuantumCircuit` をラップした [`LearingCircuit`](https://github.com/Qulacs-Osaka/scikit-qulacs/blob/3d7153fb966189486196a491aed2a65436d992bf/skqulacs/circuit/circuit.py#L64) というクラスがあります．
このクラスにはパラメータ共有の機能が実装されており，ひとつのパラメータを変更することで `ParametricQuantumCircuit` の複数のパラメータを変更することができます．

しかし，`ParametricQuantumCircuit::add_gate_copy()` によってゲートを追加すると，共有されたパラメータに不整合が生じそうであることがわかりました．
いま [scikit-qulacs#186](https://github.com/Qulacs-Osaka/scikit-qulacs/issues/186) で `LearningCircuit` に [`QuantumCircuit::merge_gate()`](https://github.com/Qulacs-Osaka/qulacs-osaka/blob/14355f20eaf3615cb78c11a76a6c014cbca1b28d/src/cppsim/circuit.hpp#L140) を使うメソッドを実装しようとしているので，その不整合が問題になります．
これを `LearningCircuit` でケアするのは難しいため，パラメータ共有の機能を `ParametricQuantumCircuit` におろそうと思います．

**Comment by WATLE** [comment]
いま自分手が空いているので、　これに関するコードをまだ書いていなければ引き受けたいです

**Comment by ikanago** [comment]
[scikit-qulacs 側でどうにかできそう](https://github.com/Qulacs-Osaka/scikit-qulacs/issues/186#issuecomment-1131288150)なのでやってもらわなくてよさそうです．いったん close します
