### ISSUE TITLE
csimの名称変更

### ISSUE THREAD

**Issue by forest1040** [Qulacs-Osaka/qulacs-osaka#349]
csimがC++化されたため、名称を変更する。
関連事項として、qulacs統合がある。
qunasysさんが、qulacsのRustバインディングを開発しており、それがcsimに依存している。
qulacsのcsimは、C言語だが、qulacs統合でC++化され、Rustバインディングに影響がでるかも知れない。（現在、影響と対応時期をqunasysさんが確認中）
そのため、C言語版のcsimを置いておく（そのうち削除する）。C++化されたcsimは別名にする。
名称検討中。。

**Comment by ikanago** [comment]
csim という名前に込められた意味は 「C で書かれた」ということだけなので，名前の変更はせずに cppsim にすべて移してしまってもいいと思います．

**Comment by WATLE** [comment]
cpp,ただでさえファイルが多いので、cppとcを混ぜたら探すのが困難になります。
また、現状cpp側でエラー処理などをし、c側で行列などの重い計算をやる　　という風に分担ができているので、ファイルの分割方法として悪くないと思います。
だから、C++化されたcsimは別名でおいておくか、なんかよい分類を見つけるのが良いと思います。

**Comment by forest1040** [comment]
qunasysさんのqulacsのRustバインディングは、現状バージョン（v0.3系）を使うとのことでしたので、
この対応は必須ではなくなりました。
ですので、現状維持でよいかなという気持ちです。。

**Comment by forest1040** [comment]
一旦クローズします。
