### ISSUE TITLE
qulacs本家の修正を取り込む

### ISSUE THREAD

**Issue by forest1040** [Qulacs-Osaka/qulacs-osaka#353]
- [Fix memory leak when creating a quantum operator by kwkbtr · Pull Request #306 · qulacs/qulacs](https://github.com/qulacs/qulacs/pull/306/files)
- [Expectation value can be wrong when using DensityMatrix (Severe bug) · Issue #314 · qulacs/qulacs](https://github.com/qulacs/qulacs/issues/314)

**Comment by ysuzuki-qc** [comment]
I have include these features in #351, and this issue is resolved.
