### ISSUE TITLE
Try probablistic test for multiple times

### ISSUE THREAD

**Issue by KowerKoint** [Qulacs-Osaka/qulacs-osaka#367]
たまにコードは正しいのにテストが落ちる。
これは開発において余計なストレスになるし、READMEのバッジがCI:failedになるのも印象が悪い。
こういうのはほとんどサンプリングの偏りなどで生じる確率的なものなのでそっちに対する統一的な対応をする。
- 「とても運が悪くてズレる」のは仕方ないのでそれがめったに(10回中2回など)起こらないことを示す
- 実装例は[#283](https://github.com/Qulacs-Osaka/qulacs-osaka/pull/283) みたいな感じ
- _CHECK_NEARという一発ではテスト自体には落とさないけどGTest風のエラーメッセージを返すマクロをここで作ってるので外でも活用したい

**Comment by ikanago** [comment]
最近 [`NoisyEvolutionTest`](https://github.com/Qulacs-Osaka/qulacs-osaka/blob/24e7aa0e8c3e53a69a1f05a4498fbf33e6a3d096/test/cppsim/test_noisyevolution.cpp#L192) が落ちてたので一応貼っておきます: https://github.com/Qulacs-Osaka/qulacs-osaka/runs/7294964972?check_suite_focus=true
