### ISSUE TITLE
pybind版のGradCalculator.calculate_gradの引数名が空白を含んでいる

### ISSUE THREAD

**Issue by herring101** [Qulacs-Osaka/qulacs-osaka#377]
https://github.com/Qulacs-Osaka/qulacs-osaka/blob/b4985b70d5d5d4191eb6ac4e04a5ae575519b011/python/cppsim_wrapper.cpp#L626
最後の引数名は`"angles of gates"`となっているが、これでは引数名として機能しなさそう

**Comment by KowerKoint** [comment]
一応動いてるけどstubが壊れてるので治す
